vllm using port  31602
[W620 13:42:03.111517798 OperatorEntry.cpp:154] Warning: Warning only once for all operators,  other operators may also be overridden.
  Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: aten::geometric_(Tensor(a!) self, float p, *, Generator? generator=None) -> Tensor(a!)
    registered at /pytorch/build/aten/src/ATen/RegisterSchema.cpp:6
  dispatch key: XPU
  previous kernel: registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:37
       new kernel: registered at /build/intel-pytorch-extension/build/Release/csrc/gpu/csrc/gpu/xpu/ATen/RegisterXPU_0.cpp:186 (function operator())
INFO 06-20 13:42:04 [__init__.py:248] Automatically detected platform xpu.
WARNING 06-20 13:42:05 [_logger.py:68] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 06-20 13:42:16 [config.py:752] This model supports multiple tasks: {'embed', 'score', 'reward', 'generate', 'classify'}. Defaulting to 'generate'.
WARNING 06-20 13:42:16 [_logger.py:68] device type=xpu is not supported by the V1 Engine. Falling back to V0. 
INFO 06-20 13:42:16 [config.py:1815] Defaulting to use mp for distributed inference
INFO 06-20 13:42:16 [config.py:1849] Disabled the custom all-reduce kernel because it is not supported on current platform.
ERROR 06-20 13:42:16 [xpu.py:104] Both start methods (spawn and fork) have issue on XPU if you use mp backend, setting it to ray instead.
INFO 06-20 13:42:16 [llm_engine.py:240] Initializing a V0 LLM engine (v0.8.5.dev562+gc44c384b1) with config: model='/scratch/group/hprc/llama-models/llama-3_3-70B', speculative_config=None, tokenizer='/scratch/group/hprc/llama-models/llama-3_3-70B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=1024, download_dir=None, load_format=auto, tensor_parallel_size=4, pipeline_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=True, kv_cache_dtype=auto,  device_config=xpu, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=None, served_model_name=/scratch/group/hprc/llama-models/llama-3_3-70B, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=True, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[],"max_capture_size":0}, use_cached_outputs=False, 
WARNING 06-20 13:42:16 [_logger.py:68] No existing RAY instance detected. A new instance will be launched with current node resources.
2025-06-20 13:42:18,353	INFO worker.py:1888 -- Started a local Ray instance.
INFO 06-20 13:42:21 [ray_utils.py:335] No current placement group found. Creating a new placement group.
INFO 06-20 13:42:22 [ray_distributed_executor.py:176] use_ray_spmd_worker: False
[36m(pid=2523724)[0m [W620 13:42:27.247933812 OperatorEntry.cpp:154] Warning: Warning only once for all operators,  other operators may also be overridden.
[36m(pid=2523724)[0m   Overriding a previously registered kernel for the same operator and the same dispatch key
[36m(pid=2523724)[0m   operator: aten::geometric_(Tensor(a!) self, float p, *, Generator? generator=None) -> Tensor(a!)
[36m(pid=2523724)[0m     registered at /pytorch/build/aten/src/ATen/RegisterSchema.cpp:6
[36m(pid=2523724)[0m   dispatch key: XPU
[36m(pid=2523724)[0m   previous kernel: registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:37
[36m(pid=2523724)[0m        new kernel: registered at /build/intel-pytorch-extension/build/Release/csrc/gpu/csrc/gpu/xpu/ATen/RegisterXPU_0.cpp:186 (function operator())
[36m(pid=2523725)[0m INFO 06-20 13:42:30 [__init__.py:248] Automatically detected platform xpu.
[36m(pid=2523725)[0m WARNING 06-20 13:42:31 [_logger.py:68] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 06-20 13:42:32 [ray_distributed_executor.py:352] non_carry_over_env_vars from config: set()
INFO 06-20 13:42:32 [ray_distributed_executor.py:354] Copying the following environment variables to workers: ['VLLM_PORT', 'LD_LIBRARY_PATH', 'VLLM_USE_V1']
INFO 06-20 13:42:32 [ray_distributed_executor.py:357] If certain env vars should NOT be copied to workers, add them to /home/u.ks124812/.config/vllm/ray_non_carry_over_env_vars.json file
INFO 06-20 13:42:32 [xpu.py:35] Cannot use None backend on XPU.
INFO 06-20 13:42:32 [xpu.py:36] Using IPEX attention backend.
[36m(RayWorkerWrapper pid=2523725)[0m INFO 06-20 13:42:32 [xpu.py:35] Cannot use None backend on XPU.
[36m(RayWorkerWrapper pid=2523725)[0m INFO 06-20 13:42:32 [xpu.py:36] Using IPEX attention backend.
INFO 06-20 13:42:32 [shm_broadcast.py:266] vLLM message queue communication handle: Handle(local_reader_ranks=[1, 2, 3], buffer_handle=(3, 4194304, 6, 'psm_591239e5'), local_subscribe_addr='ipc:///tmp/job.1187908/931a26ce-aeb2-4f96-9351-acb05801ba20', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 06-20 13:42:32 [parallel_state.py:1004] rank 0 in world size 4 is assigned as DP rank 0, PP rank 0, TP rank 0
2025:06:20-13:42:32:(2523181) |CCL_WARN| value of CCL_ATL_TRANSPORT changed to be ofi (default:mpi)
2025:06:20-13:42:32:(2523181) |CCL_WARN| value of CCL_LOCAL_RANK changed to be 0 (default:-1)
2025:06:20-13:42:32:(2523181) |CCL_WARN| value of CCL_LOCAL_SIZE changed to be 4 (default:-1)
2025:06:20-13:42:32:(2523181) |CCL_WARN| value of CCL_PROCESS_LAUNCHER changed to be none (default:hydra)
2025:06:20-13:42:33:(2523181) |CCL_WARN| pidfd is not supported, fallbacks to drmfd exchange mode
[36m(RayWorkerWrapper pid=2523725)[0m INFO 06-20 13:42:32 [parallel_state.py:1004] rank 1 in world size 4 is assigned as DP rank 0, PP rank 0, TP rank 1
[36m(RayWorkerWrapper pid=2523725)[0m 2025:06:20-13:42:33:(2523725) |CCL_WARN| pidfd is not supported, fallbacks to drmfd exchange mode
Loading safetensors checkpoint shards:   0% Completed | 0/30 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   3% Completed | 1/30 [00:01<00:32,  1.12s/it]
Loading safetensors checkpoint shards:   7% Completed | 2/30 [00:02<00:32,  1.15s/it]
Loading safetensors checkpoint shards:  10% Completed | 3/30 [00:03<00:30,  1.13s/it]
Loading safetensors checkpoint shards:  13% Completed | 4/30 [00:04<00:27,  1.04s/it]
Loading safetensors checkpoint shards:  17% Completed | 5/30 [00:05<00:24,  1.03it/s]
Loading safetensors checkpoint shards:  20% Completed | 6/30 [00:05<00:21,  1.09it/s]
Loading safetensors checkpoint shards:  23% Completed | 7/30 [00:06<00:20,  1.15it/s]
Loading safetensors checkpoint shards:  27% Completed | 8/30 [00:07<00:18,  1.20it/s]
Loading safetensors checkpoint shards:  30% Completed | 9/30 [00:08<00:17,  1.21it/s]
Loading safetensors checkpoint shards:  33% Completed | 10/30 [00:09<00:16,  1.23it/s]
Loading safetensors checkpoint shards:  37% Completed | 11/30 [00:09<00:14,  1.35it/s]
Loading safetensors checkpoint shards:  40% Completed | 12/30 [00:10<00:13,  1.34it/s]
Loading safetensors checkpoint shards:  43% Completed | 13/30 [00:11<00:12,  1.37it/s]
Loading safetensors checkpoint shards:  47% Completed | 14/30 [00:11<00:11,  1.37it/s]
Loading safetensors checkpoint shards:  50% Completed | 15/30 [00:12<00:11,  1.35it/s]
Loading safetensors checkpoint shards:  53% Completed | 16/30 [00:13<00:09,  1.41it/s]
Loading safetensors checkpoint shards:  57% Completed | 17/30 [00:14<00:09,  1.38it/s]
Loading safetensors checkpoint shards:  60% Completed | 18/30 [00:14<00:06,  1.73it/s]
Loading safetensors checkpoint shards:  63% Completed | 19/30 [00:14<00:06,  1.68it/s]
Loading safetensors checkpoint shards:  67% Completed | 20/30 [00:15<00:06,  1.61it/s]
Loading safetensors checkpoint shards:  70% Completed | 21/30 [00:16<00:05,  1.57it/s]
Loading safetensors checkpoint shards:  73% Completed | 22/30 [00:16<00:05,  1.56it/s]
Loading safetensors checkpoint shards:  77% Completed | 23/30 [00:17<00:04,  1.56it/s]
Loading safetensors checkpoint shards:  80% Completed | 24/30 [00:18<00:04,  1.50it/s]
Loading safetensors checkpoint shards:  83% Completed | 25/30 [00:18<00:03,  1.49it/s]
Loading safetensors checkpoint shards:  87% Completed | 26/30 [00:19<00:02,  1.52it/s]
Loading safetensors checkpoint shards:  90% Completed | 27/30 [00:20<00:01,  1.55it/s]
Loading safetensors checkpoint shards:  93% Completed | 28/30 [00:20<00:01,  1.63it/s]
Loading safetensors checkpoint shards:  97% Completed | 29/30 [00:21<00:00,  1.62it/s]
Loading safetensors checkpoint shards: 100% Completed | 30/30 [00:21<00:00,  1.63it/s]
Loading safetensors checkpoint shards: 100% Completed | 30/30 [00:21<00:00,  1.37it/s]

[36m(RayWorkerWrapper pid=2523727)[0m INFO 06-20 13:43:02 [default_loader.py:278] Loading weights took 18.94 seconds
[36m(RayWorkerWrapper pid=2523727)[0m WARNING 06-20 13:43:02 [_logger.py:68] Pin memory is not supported on XPU.
[36m(pid=2523727)[0m INFO 06-20 13:42:30 [__init__.py:248] Automatically detected platform xpu.[32m [repeated 3x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)[0m
[36m(pid=2523727)[0m WARNING 06-20 13:42:31 [_logger.py:68] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")[32m [repeated 3x across cluster][0m
[36m(RayWorkerWrapper pid=2523727)[0m INFO 06-20 13:42:32 [xpu.py:35] Cannot use None backend on XPU.[32m [repeated 2x across cluster][0m
[36m(RayWorkerWrapper pid=2523727)[0m INFO 06-20 13:42:32 [xpu.py:36] Using IPEX attention backend.[32m [repeated 2x across cluster][0m
[36m(RayWorkerWrapper pid=2523727)[0m INFO 06-20 13:42:32 [parallel_state.py:1004] rank 3 in world size 4 is assigned as DP rank 0, PP rank 0, TP rank 3[32m [repeated 2x across cluster][0m
[36m(RayWorkerWrapper pid=2523727)[0m 2025:06:20-13:42:33:(2523727) |CCL_WARN| pidfd is not supported, fallbacks to drmfd exchange mode[32m [repeated 2x across cluster][0m
[36m(RayWorkerWrapper pid=2523727)[0m INFO 06-20 13:43:03 [xpu_model_runner.py:414] Loading model weights took 32.8894 GiB
INFO 06-20 13:43:05 [default_loader.py:278] Loading weights took 22.02 seconds
WARNING 06-20 13:43:05 [_logger.py:68] Pin memory is not supported on XPU.
INFO 06-20 13:43:06 [xpu_model_runner.py:414] Loading model weights took 32.8894 GiB
2025:06:20-13:43:07:(2523181) |CCL_WARN| pidfd is not supported, fallbacks to drmfd exchange mode
INFO 06-20 13:43:24 [executor_base.py:112] # xpu blocks: 8446, # CPU blocks: 3276
INFO 06-20 13:43:24 [executor_base.py:117] Maximum concurrency for 1024 tokens per request: 131.97x
INFO 06-20 13:43:25 [llm_engine.py:435] init engine (profile, create kv cache, warmup model) took 18.52 seconds
 * Serving Flask app 'app'
 * Debug mode: off
2025-06-20 13:43:25,154 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:1025
 * Running on http://127.0.0.1:1025
2025-06-20 13:43:25,154 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
